# Generated by Django 5.2.8 on 2025-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('tier', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('icon_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
