# Generated by Django 5.2.8 on 2025-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttoorder',
            options={'verbose_name': 'Продукт для заказа', 'verbose_name_plural': 'Продукты для заказа'},
        ),
        migrations.AlterField(
            model_name='producttoorder',
            name='icon_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producttoorder',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producttoorder',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producttoorder',
            name='tier',
            field=models.TextField(blank=True, choices=[(1, 'tier1'), (2, 'tier2'), (3, 'tier3'), (4, 'tier4'), (5, 'tier5'), (6, 'tier6'), (7, 'tier7'), (8, 'tier8'), (9, 'tier9')], null=True),
        ),
    ]
