# Generated by Django 5.2.8 on 2025-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_producttoorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoorder',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(1, 'tier1'), (2, 'tier2'), (3, 'tier3'), (4, 'tier4'), (5, 'tier5'), (6, 'tier6'), (7, 'tier7'), (8, 'tier8'), (9, 'tier9')], null=True),
        ),
    ]
