# Generated by Django 5.2.8 on 2025-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
