# Generated by Django 5.2.8 on 2025-11-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='progress',
            new_name='saves',
        ),
    ]
